"""Create a baseline migrations

Revision ID: 824f7e276015
Revises: 18f07b9b5648
Create Date: 2024-06-05 11:44:38.657876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824f7e276015'
down_revision: Union[str, None] = '18f07b9b5648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Calculation1',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numbers', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('calculation_type', sa.Enum('SUM', 'SUBTRACTION', 'MULTIPLICATION', 'DIVISION', name='calculationtype'), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Calculation1')
    # ### end Alembic commands ###
